language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
# There's no nicer way to specify this matrix; see
# https://github.com/travis-ci/travis-ci/issues/1519.
matrix:
  include: 
    - jdk: oraclejdk8 
      scala: 2.11.8
      env: TEST_HADOOP_VERSION="2.7.3" TEST_SPARK_VERSION="2.2.0"
    - jdk: oraclejdk8
      scala: 2.11.8
      env: TEST_HADOOP_VERSION="2.2.0" TEST_SPARK_VERSION="2.1.0"
script:
  - sbt -Dhadoop.testVersion=$TEST_HADOOP_VERSION -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION coverage test
after_success:
  - bash <(curl -s https://codecov.io/bash)
